language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
install:
  pip install nose coverage coveralls
script:
  - nosetests --cover-branches --with-coverage --cover-erase --verbose --cover-package=exceptive
after_success: coveralls
